### ISSUE TITLE
Apple Silicon Editor Issue

### ISSUE THREAD

**Issue by heisarzola** [GameWorkstore/com.google.firebase.app#15] opened 2023-05-19 16:52 UTC
Hello, 

I've recently decided to port an existing project that made use of the 10.6.0 version of the different tools to iOS, however this was somewhat short lived because I quickly encountered this error message:

![image](https://github.com/GameWorkstore/com.google.firebase.app/assets/34221560/40a644f5-9bd4-4adb-81a7-e50d49653ef1)

The gist of it is that my current mac pc is that of an apple mini which features an m1 chip a.k.a. apple silicon. And the problem seems to be that, as the error illustrates, more than one of the core dlls are marked as "enabled for the unity editor", given that one is marked as "enabled for everything":

![image](https://github.com/GameWorkstore/com.google.firebase.app/assets/34221560/cedc5b46-2fc0-49f0-a872-018dd6f154a2)
![image](https://github.com/GameWorkstore/com.google.firebase.app/assets/34221560/145e0786-82f1-4f24-892a-60702d9ec6ce)

These dlls are located in the arm64 and x86_64 folders respectively:
![image](https://github.com/GameWorkstore/com.google.firebase.app/assets/34221560/a0ec6c86-038d-4cc7-88c0-8208f99e3442)

Needless to say, this makes the firebase packages unusable on apple silicon, since you cannot manually edit the platform settings of the dlls as they are grayed out.

Would there be a chance this could be fixed? 
Thank you in advance.

**Comment by snorrsi** [comment] 2023-05-19 17:20
Hi @heisarzola ,

I used to use Mac Mini M1 myself and it worked fine for me.
I split this bundle into two files using lipo due to size of the orginal file.
I created a new branch and removed the OSXUniversal as only OSXIntel64 should be needed for the x86_64 file.

Can you please try the branch osx-10.6.0 instead of 10.6.0 ?

**Comment by heisarzola** [comment] 2023-05-31 00:34
Apologies for the very late reply, despite the very fast initial response. 
As far as I can tell the problem persists even on that new branch, given a very similar issue where the files in the `arm64` and `x86_64` shown above both have the `Editor` platform ticked.

![image](https://github.com/GameWorkstore/com.google.firebase.app/assets/34221560/5fef3bc0-93d1-4550-bbd4-b73ddc3c0514)

I think that I'll play around with not using the package manager version, manually adding the files, and experimenting with the platform settings to see what works, then get back to you to report my findings.

**Comment by heisarzola** [comment] 2023-05-31 01:25
After making a local package and playing around with the settings, I can confirm that if the `.bundle` file on `x86_64` is fully disabled (meaning `Editor` is no longer a platform it's active at, nor is any), I can successfully boot my project like I would on any non-apple platform. This is the only one that needs to be edited on that folder.

Though unfortunately, and uniquely odd as it might seem, I keep getting an issue related with cocoapods with this setup which on some forum hopping suggest might be caused by the fact I'm using a local package to build (or at least is worth checking if this is indeed the problem). So if it isn't much trouble, can the osx branch be updated with the changes mentioned above?

**Comment by snorrsi** [comment] 2023-06-02 18:44
Hi @heisarzola ,

I updated the osx-10.6.0 and upm branch and created tag 11.1.0 with OSX and x86_64 specified.
Can you check if that works for you ?

**Comment by noname77** [comment] 2023-07-05 21:14
hey,

I've seen this issue with `10.1.1` and after updating to `11.1.0` things seem to work as expected on an m1 Mac in apple silicon unity editor

thanks!

**Comment by snorrsi** [comment] 2023-07-05 21:31
closed as confirmed working in 11.1.0

**Closed by snorrsi** 2023-07-05 21:31 UTC

**Comment by ilufang** [comment] 2024-02-05 05:52
Hello,

It seems that this issue has reappeared as I am trying to use 11.6.0 upm package with an apple silicon unity editor (2021.3.33f1).

The platform setting of the x86_64 bundle [had been correctly set as `x86_64` in 11.1.0](https://github.com/GameWorkstore/com.google.firebase.app/blob/11.1.0/Firebase/Plugins/x86_64/FirebaseCppApp-11_1_0.bundle.meta#L24) but was then [reverted back to `AnyCPU` in 11.2.0 and onwards](https://github.com/GameWorkstore/com.google.firebase.app/blob/11.2.0/Firebase/Plugins/x86_64/FirebaseCppApp-11_2_0.bundle.meta#L24), causing an apple silicon editor to once again attempt to load it on top of the arm64 bundle.

Manually updating `x86_64/FirebaseCppApp-11_6_0.bundle.meta` (line 24 and 48) successfully clears the issue for me.

Could you help locate and verify that the fix still exists in recent versions? Thanks!
